application:
  name: chef-oeuvre
  project: chef-oeuvre
  ram: 2GB
  publicly_accessible: true
  storage:
    - name: images
      type: ssd
      size: 10GB
      mount_point: /mnt/images/uploads
routers:
- name: main
  routes:
  - application_name: app
    paths:
    - /*
